package Services;

public enum CTriggerConditionEnum {

	CT_PLAYER_RADIUS_XYZ,
	CT_PLAYER_BOXED_IN_XYZ,
	CT_PROXMITY_ENEMY_PLAYER,
	CT_LIFE_OF_PLAYER_BELOW_X_PERCENT,
	CT_OBJECT_X_IN_INVENTORY,
	CT_OBJECT_X_EQUIPPED,
	CT_PLAYER_KILLED,
	CT_PLAYER_REACHED_X_LEVEL,
	CT_PLAYER_TALKED_TO_CHAR_X,
	CT_PLAYER_KILLED_ENEMY_X,
	CT_PLAYER_RECEIVED_MESSAGE_X
}
