package Services;

public enum CTriggerResponseEnum {

	
	CT_LEVEL_QUEST_COMPLETE,
	CT_HURT_HEAL_PLAYER_BY_X_PTS,
	CT_GIVE_PLAYER_EXPERIENCE,
	CT_OPEN_CLOSE_LOCK_UNLOCK_DOOR,
	CT_SPAWM_X_CREATURES_OF_TYPE_Y,
	CT_KILL_X_CREATURES,
	CT_PLAY_SOUND,
	CT_PLAY_RANDOM_SOUND_FROM_LIST,
	CT_X_CHANCE_OF_PLAYING_SOUND,
	CT_MOVE_PLAYER_ENEMY_X_TO_POINT,
	CT_SPAWN_SPECIAL_EFFECT_IN_SPOT_OF_ENEMY_PLAYER,
	CT_SET_PLAYER_ENEMY_ON_FIRE,
	CT_POISON_PLAYER_ENEMY,
	CT_STUN_PLAYER_ENEMY,
	CT_MAKE_PLAYER_ENEMY_INVINCIBLE,
	CT_MAKE_PLAYER_ENEMY_INVISIBLE,
	CT_RESET_TRIGGER,
	CT_SEND_MESSAGE_X_TO_PLAYER
	
}
