package AI.BitTables.Character;

public class CAdvancedAISliders {

	
	
	/* Advanced Statistics (meters/sliders)
COGNITION –, PERCIEVING, PLANNING, IMAGING, DREAMING,
Cognition
o	IMPLEMENT MEMORY – SHORT TERM AND LONG TERM
o	INTELLIGENCE – ABILITY TO LEARN AND ADAPT
o	THINKING
o	PERCEIVING
o	PLANNING
o	IMAGING
o	DREAMING
o	PROBLEM SOLVING
o	ATTENTION TO REWARDS AND DANGER
o	PATH-FINDING
o	INHIBITION
o	


Personalities
o	PERSONALITIES – THE FIELD OF PERSONALITY FOCUSES ON MORE OR LESS TENDENCIES BEHAVING ACCORDING TO OUR PERSONALITIES
o	ATTITUDES
o	BELIEFS
o	SKILLS
o	MOTIVATION AND EMOTION
o	HUNGER
o	THIRST
o	 SEX
o	NEED FOR ACHIEVING
o	NEED FOR RELATIONSHIPS WITH OTHERS


Autonomic System

o	HEART BEAT
o	BREATHING
o	DIGESTION
o	SWEATING
o	SPEAKING
o	LISTENING
o	ADRENAL GLANDS – EPINEPHRINE AND NOREPINEPHRINE
	STIMULATE CHANGES TO THE BODY WHICH  INTENSE ACTIVITY
o	EPINEPHRINE – INREASES BLOOD PRESSURE AND FLOW AND CHANGES METABOLISM
o	NOREPINEPHRINE – INCREASES BLOOD PRESSURE AS WELL
o	PITUATARY GLAND – ROLE ON BLOOOD PRESSURE, THIRST, AND BODY GROWTH
o	OCCIPITAL AREA – CONTROLS THE VISUAL BEHAVIOR
o	MELATONIN – SECRETED BY THE PINEAL GLAND CONTROLS SLEEP CYCLE
o	WEATHER

*/
	
}
