package AI.BitTables.Character;

public class CSocialBehaviorsSliders {
/* Social Behaviors
o	SOCIAL PSYCHOLOGY – WAYS PEOPLE BEHAVE IN CROWDS, GROUPS, MOBS, ORGANIATIONS; INTERPERSONAL INTERACTION, ATTITUDE AND PREJUDICE TOWARDS OTHERS (flocking algorithm for example)
o	FRIENDSHIP
o	CONVERSATIONAL
o	
o	HUMANS ARE SOCIAL ANIMALS – LIKE BEES AND GEESE HUMANS FLOCK IN  SOCIAL GROUPS.  HUMANS WORK TOGETHER TO ACHIEVE A GOAL WHEN NECESSARY
o	SOCIOCULTURAL DIFFERENCES (NOT ALL MEMBERS OF A CULTURE HAVE THE SAME TRAITS LIKE HEIGHT, WEIGHT, COGNITION, ETC) LOYALTIES
o	ETHNIC IDENTITY
GENDER IDENTITY
o	FRONT LOBE – CONTROL AND INHIBITION ON SOCIAL BEHAVIOR MOODS



*/
	
	
}
